### ISSUE TITLE
[BUG] Custom Domain Search is broken with Dark-Lite Theme

### ISSUE THREAD

**Issue by FuryCraft** [WybeNetwork/VistaPanel-Themes#11] opened 2022-01-15 18:01 UTC
We can't view the tld selection.
![image](https://user-images.githubusercontent.com/44116544/149632647-21f1b38a-9350-4cf3-90f9-3218757d62d4.png)

**Comment by 4yx** [comment] 2022-02-02 16:00
I cannot reproduce this, a similar issue occurs to me when using Responsive Domain Search but the TLDs appear when I click on the dropdown. Do they not load at all here?

**Comment by 4yx** [comment] 2022-08-03 15:08
@FuryCraft, can you please confirm if this is still an issue?

**Comment by FuryCraft** [comment] 2022-08-04 13:43
Yes tlds are only loaded on selection

**Comment by 4yx** [comment] 2022-08-05 17:18
I was able to locate the issue; apparently the Dark themes feature a patch from einet which makes the domain search already responsive; this naturally breaks the Responsive Domain Search script.
I'm currently considering what to do, which will probably be an attempt to undo einet's modifications in the script's favor.

Expect a fix to be pushed soon.

**Comment by 4yx** [comment] 2022-08-07 22:20
I will be off for the next 3-4 days so I probably will not be able to work on this, sorry; a temporary solution would be to comment out/remove the Responsive Domain Search script's lines, as dark-lite makes the domain search already responsive as mentioned.
I'll work on this as soon as I return, again, my apologies for the delay.

**Comment by 4yx** [comment] 2022-08-26 16:35
@FuryCraft (sorry for mentioning you again), can you confirm if my latest commit fixed the issue?

**Comment by 4yx** [comment] 2022-08-28 16:34
Since it's working in my tests I'm closing it as fixed in 6baa56b90a13f3e90e6b7c79e82f8d636ac3712d. Feel free to (ask me to) reopen it if you still face the issue.

**Closed by 4yx** 2022-08-28 16:34 UTC
Labels: bug
